services:
  nginx:
    image: nginx:1.29-alpine
    container_name: nginx-front
    restart: unless-stopped
    environment:
      MAIN_NGINX_HOST_IP: ${MAIN_NGINX_HOST_IP}
      DOMAIN_NAME: example.com
      NGINX_ENVSUBST_OUTPUT_DIR: "/etc/nginx"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/:/etc/nginx/templates/:ro
      - /etc/letsencrypt/live:/etc/letsencrypt/live:ro
      - /etc/letsencrypt/archive:/etc/letsencrypt/archive:ro
      - /etc/letsencrypt/renewal:/etc/letsencrypt/renewal:ro
      - /etc/ssl/certs:/etc/ssl/certs:ro

